In [2]:
import os
os.environ['CUDA_LAUNCH_BLOCKING'] = '1'
# Este comando nos permitirá realizar un seguimiento de la depuración ocurrida durante el uso de CUDA


import torch
from torch import nn
from tqdm.auto import tqdm
from torchvision import transforms
from torchvision.utils import make_grid, save_image
from torch.utils.data import DataLoader, Dataset
import torchvision.transforms as T
import torchvision.datasets as dtst
from torch import optim

from PIL import Image

import random
import os
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# Retiramos los mensajes de alerta
import warnings
warnings.filterwarnings('ignore')

# Inicializamos las semillas de los valores aleatorios
random.seed(99)
torch.manual_seed(99)

%matplotlib inline

In [3]:
data_folder = './images'

# Tamaño que deseamos que tengan las imágenes
image_size = 128
# Tamaño del lote de imágenes
batch_size = 64


dsimgs = dtst.ImageFolder(
    root=data_folder,
    transform=transforms.Compose([
        # Se usa el resize en caso no todas las imágenes de entrada tengan el tamaño de 128px
        transforms.Resize(image_size),
        # CenterCrop busca recortar la imagen en caso sea muy grande al tamaño dado
        transforms.CenterCrop(image_size),
        # ToTensor convierte finalmente la imagen a tensor
        transforms.ToTensor()
        # Normalize permite la normalización de la información
        # El problema encontrado es que necesitamos hallar la desviación estandar
        # media de toda la información para realizar una correcta normalización
        
    ]))

In [5]:
dsimgs

Dataset ImageFolder
    Number of datapoints: 41512
    Root location: ./images
    StandardTransform
Transform: Compose(
               Resize(size=128, interpolation=bilinear, max_size=None, antialias=None)
               CenterCrop(size=(128, 128))
               ToTensor()
           )

In [6]:
dt_loader = DataLoader(dsimgs,
                       batch_size=batch_size,
                       shuffle=True,
                       num_workers=1,
                       drop_last=True)

In [ ]:
dt_loader

In [40]:
list_r=[]
list_g=[]
list_b=[]

for real, _ in dt_loader:
#     print(real[63].shape)
    list_r.append(real[0,:,:].mean().float())   
    list_g.append(real[1,:,:].mean().float())   
    list_b.append(real[2,:,:].mean().float())   

In [56]:
list_r_d=[]
list_g_d=[]
list_b_d=[]

for real, _ in dt_loader:
#     print(real[63].shape)
    i=0
    list_r_d.append((real[0,:,:]**2).mean().float()-list_r[i]**2)   
    list_g_d.append((real[1,:,:]**2).mean().float()-list_g[i]**2)   
    list_b_d.append((real[2,:,:]**2).mean().float()-list_b[i]**2)
    i=i+1

In [55]:
import statistics

print(len(list_b))

print(torch.mean(torch.stack(list_r)))
print(torch.mean(torch.stack(list_g)))
print(torch.mean(torch.stack(list_b)))

648
tensor(0.6134)
tensor(0.6145)
tensor(0.6188)


In [64]:
print(list_r)

[tensor(0.5238), tensor(0.7366), tensor(0.6058), tensor(0.6941), tensor(0.8079), tensor(0.5185), tensor(0.4516), tensor(0.4548), tensor(0.5160), tensor(0.4713), tensor(0.5938), tensor(0.5201), tensor(0.6375), tensor(0.4173), tensor(0.6818), tensor(0.6083), tensor(0.5658), tensor(0.5390), tensor(0.5908), tensor(0.5474), tensor(0.6639), tensor(0.5409), tensor(0.5807), tensor(0.7043), tensor(0.7000), tensor(0.6063), tensor(0.6788), tensor(0.7574), tensor(0.5423), tensor(0.6287), tensor(0.7483), tensor(0.6027), tensor(0.7550), tensor(0.7950), tensor(0.7495), tensor(0.6141), tensor(0.5673), tensor(0.6711), tensor(0.5256), tensor(0.7362), tensor(0.6483), tensor(0.7367), tensor(0.6952), tensor(0.5330), tensor(0.4871), tensor(0.5002), tensor(0.4232), tensor(0.5941), tensor(0.6844), tensor(0.5033), tensor(0.6272), tensor(0.4484), tensor(0.4296), tensor(0.7862), tensor(0.7557), tensor(0.4173), tensor(0.7050), tensor(0.4683), tensor(0.6340), tensor(0.7349), tensor(0.5363), tensor(0.5582), tensor(

In [57]:

print(torch.sqrt(torch.mean(torch.stack(list_r_d))))
print(torch.sqrt(torch.mean(torch.stack(list_g_d))))
print(torch.sqrt(torch.mean(torch.stack(list_b_d))))

tensor(0.4335)
tensor(0.4493)
tensor(nan)


In [58]:
list_r_d2=[]
list_g_d2=[]
list_b_d2=[]

for real, _ in dt_loader:
#     print(real[63].shape)
    list_r_d2.append(torch.std_mean(real[0,:,:]))   
    list_g_d2.append(torch.std_mean(real[1,:,:]))   
    list_b_d2.append(torch.std_mean(real[2,:,:]))

In [65]:
for i in list_b_d2:
    print(i)

(tensor(0.3094), tensor(0.3898))
(tensor(0.2849), tensor(0.4702))
(tensor(0.3118), tensor(0.5212))
(tensor(0.3109), tensor(0.5805))
(tensor(0.2081), tensor(0.7235))
(tensor(0.2527), tensor(0.6668))
(tensor(0.2589), tensor(0.5799))
(tensor(0.2454), tensor(0.6128))
(tensor(0.2403), tensor(0.6251))
(tensor(0.2509), tensor(0.7247))
(tensor(0.2461), tensor(0.4582))
(tensor(0.2843), tensor(0.4239))
(tensor(0.2842), tensor(0.5839))
(tensor(0.2969), tensor(0.7101))
(tensor(0.3081), tensor(0.6336))
(tensor(0.2831), tensor(0.5150))
(tensor(0.2820), tensor(0.4948))
(tensor(0.2300), tensor(0.7510))
(tensor(0.2626), tensor(0.6364))
(tensor(0.2509), tensor(0.6792))
(tensor(0.2662), tensor(0.6484))
(tensor(0.2530), tensor(0.6104))
(tensor(0.2245), tensor(0.7506))
(tensor(0.2445), tensor(0.7000))
(tensor(0.1879), tensor(0.8157))
(tensor(0.2861), tensor(0.5911))
(tensor(0.2770), tensor(0.5958))
(tensor(0.3133), tensor(0.5812))
(tensor(0.2987), tensor(0.4562))
(tensor(0.3222), tensor(0.4661))
(tensor(0.

(tensor(0.2989), tensor(0.4077))
(tensor(0.2709), tensor(0.7233))
(tensor(0.1984), tensor(0.7989))
(tensor(0.2506), tensor(0.7074))
(tensor(0.2397), tensor(0.5973))
(tensor(0.3578), tensor(0.4428))
(tensor(0.2555), tensor(0.5953))
(tensor(0.1799), tensor(0.7663))
(tensor(0.2145), tensor(0.7419))
(tensor(0.1763), tensor(0.8167))
(tensor(0.3114), tensor(0.4555))
(tensor(0.2006), tensor(0.7523))
(tensor(0.2645), tensor(0.5025))
(tensor(0.2786), tensor(0.5763))
(tensor(0.2633), tensor(0.6602))
(tensor(0.3134), tensor(0.5943))
(tensor(0.2377), tensor(0.7930))
(tensor(0.2640), tensor(0.7130))
(tensor(0.2138), tensor(0.7393))
(tensor(0.2238), tensor(0.6481))
(tensor(0.3157), tensor(0.4432))
(tensor(0.2913), tensor(0.3846))
(tensor(0.3495), tensor(0.5367))
(tensor(0.2338), tensor(0.5992))
(tensor(0.2763), tensor(0.6294))
(tensor(0.2735), tensor(0.5913))
(tensor(0.3095), tensor(0.5986))
(tensor(0.1902), tensor(0.7031))
(tensor(0.3165), tensor(0.5788))
(tensor(0.2129), tensor(0.7345))
(tensor(0.

In [74]:
list_b_1 = []
list_b_2 = []
for i,j in list_b_d2:
    list_b_1.append(i)
    list_b_2.append(j)
    

In [75]:
list_b_11 = torch.mean(torch.stack(list_b_1))
list_b_21 = torch.mean(torch.stack(list_b_2))

In [76]:
list_b_11

tensor(0.2666)

In [77]:
list_b_21

tensor(0.6114)

In [78]:
list_g_1 = []
list_g_2 = []  
for i,j in list_g_d2:
    list_g_1.append(i)
    list_g_2.append(j)

list_r_1 = []
list_r_2 = []
for i,j in list_r_d2:
    list_r_1.append(i)
    list_r_2.append(j)

In [79]:
list_g_11 = torch.mean(torch.stack(list_g_1))
list_g_21 = torch.mean(torch.stack(list_g_2))

list_r_11 = torch.mean(torch.stack(list_r_1))
list_r_21 = torch.mean(torch.stack(list_r_2))

In [80]:
print(list_g_11, list_g_21)

tensor(0.2610) tensor(0.6268)


In [81]:
print(list_r_11, list_r_21)

tensor(0.2659) tensor(0.6130)


In [2]:
import torch
model = torch.hub.load('pytorch/vision:v0.10.0', 'resnet18', pretrained=True)
# or any of these variants
# model = torch.hub.load('pytorch/vision:v0.10.0', 'resnet34', pretrained=True)
# model = torch.hub.load('pytorch/vision:v0.10.0', 'resnet50', pretrained=True)
# model = torch.hub.load('pytorch/vision:v0.10.0', 'resnet101', pretrained=True)
# model = torch.hub.load('pytorch/vision:v0.10.0', 'resnet152', pretrained=True)
model.eval()

Using cache found in C:\Users\kpm_1/.cache\torch\hub\pytorch_vision_v0.10.0
Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to C:\Users\kpm_1/.cache\torch\hub\checkpoints\resnet18-f37072fd.pth


  0%|          | 0.00/44.7M [00:00<?, ?B/s]

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
  

In [6]:
model

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
  

In [ ]:
class redDiscriminadora(nn.Module):
    def __init__(self, dim_z=200, ch_rgb=3, hidd_ch=64):
        
        super(redDiscriminadora, self).__init__()
        
        self.z_dim=dim_z
        # Necesitamos realizar el proceso inverso
        self.main = nn.Sequential(
            # la entrada sería 3*128*128
            self.gen_blocks(ch_rgb, hidd_ch),
            self.gen_blocks(hidd_ch, hidd_ch),
            self.gen_blocks(hidd_ch, hidd_ch*2),
            self.gen_blocks(hidd_ch*2, hidd_ch*4),
            self.gen_blocks(hidd_ch*4, hidd_ch*8),
            self.gen_blocks(hidd_ch*8, 1,f_layer=True)  # Obtenemos un "Tensor" 1*128*128
        )
    # Para mejorar la estética y evitar redundancia de código se usa una función generadora de bloques secuenciales
    def gen_blocks(self, inp_ch, out_ch, kernel=4, stride=2, padding=1, f_layer=False):
        if not f_layer:
            return nn.Sequential(
                nn.Conv2d(inp_ch, out_ch, kernel, stride, padding, bias = False), # Probando bias = False
                nn.BatchNorm2d(out_ch),
                nn.LeakyReLU( inplace=True)
            )
        else:
            return nn.Sequential(
                nn.Conv2d(inp_ch, out_ch, kernel, 1, 0, bias = False),
                nn.Sigmoid()
            )
        
        
    def forward(self, input_arr):
        y = self.main(input_arr)
        return y.view(len(y), -1)

In [7]:
# model = torch.hub.load('pytorch/vision:v0.10.0', 'resnet18', pretrained=True)
# or any of these variants
model2 = torch.hub.load('pytorch/vision:v0.10.0', 'resnet34', pretrained=True)
# model = torch.hub.load('pytorch/vision:v0.10.0', 'resnet50', pretrained=True)
# model = torch.hub.load('pytorch/vision:v0.10.0', 'resnet101', pretrained=True)
# model = torch.hub.load('pytorch/vision:v0.10.0', 'resnet152', pretrained=True)
model2.eval()

Using cache found in C:\Users\kpm_1/.cache\torch\hub\pytorch_vision_v0.10.0
Downloading: "https://download.pytorch.org/models/resnet34-b627a593.pth" to C:\Users\kpm_1/.cache\torch\hub\checkpoints\resnet34-b627a593.pth


  0%|          | 0.00/83.3M [00:00<?, ?B/s]

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
  

In [10]:
import torch.nn as nn
import torch

# pool of square window of size=3, stride=2
m = nn.AvgPool2d(6, stride=1)
# pool of non-square window
# m = nn.AvgPool2d(2)
input = torch.randn(6,6,6)
print('########')
print(input)
output = m(input)
print('########')
print(output)

########
tensor([[[ 1.0083, -0.4761, -0.4273,  0.0387, -0.3786, -0.0781],
         [ 0.4278, -0.5613,  0.2452, -0.2636, -0.6475, -0.6469],
         [ 1.6446, -0.1629,  0.7711, -0.5876,  0.4439,  1.9078],
         [ 0.3066,  0.4844,  0.0432,  0.3786, -1.2087,  0.5091],
         [ 0.6042,  0.1448, -0.7015, -0.9291, -0.2092, -0.0070],
         [ 1.3501,  0.7757, -0.5407, -0.6645,  0.3473, -0.0482]],

        [[-0.4951, -0.4273,  0.4197, -0.9586, -0.6651,  2.3684],
         [ 0.8673,  1.7543,  0.0346, -0.1023,  0.6514, -0.4703],
         [ 0.0598, -0.5231,  2.1681,  0.4273,  1.1144,  0.3807],
         [-2.3568, -0.6518, -0.6550,  1.0352, -0.0619,  0.6226],
         [ 0.1649,  0.7319, -1.3704, -1.1830,  0.1528, -0.4004],
         [ 1.0432,  2.2963, -0.3127,  0.1884, -0.6242, -1.4861]],

        [[-0.8237, -0.5084, -0.7774, -0.6410, -1.2019,  1.0415],
         [ 0.4631, -1.0239, -0.8442,  0.3804, -0.8742, -0.3651],
         [-0.7925,  0.8926,  0.3491, -0.1281,  0.8988,  0.2211],
         [-0

In [8]:
import torchvision.models as models

In [10]:
vgg16 = models.vgg16(pretrained=True)

Downloading: "https://download.pytorch.org/models/vgg16-397923af.pth" to C:\Users\kpm_1/.cache\torch\hub\checkpoints\vgg16-397923af.pth


  0%|          | 0.00/528M [00:00<?, ?B/s]

In [11]:
vgg16.eval()

VGG(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU(inplace=True)
    (2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (3): ReLU(inplace=True)
    (4): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (5): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (6): ReLU(inplace=True)
    (7): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (8): ReLU(inplace=True)
    (9): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (10): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): ReLU(inplace=True)
    (12): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (13): ReLU(inplace=True)
    (14): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (15): ReLU(inplace=True)
    (16): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1

In [16]:
inc = models.alexnet(pretrained=True)

Downloading: "https://download.pytorch.org/models/alexnet-owt-7be5be79.pth" to C:\Users\kpm_1/.cache\torch\hub\checkpoints\alexnet-owt-7be5be79.pth


  0%|          | 0.00/233M [00:00<?, ?B/s]

In [17]:
inc.eval()

AlexNet(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(11, 11), stride=(4, 4), padding=(2, 2))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
    (3): Conv2d(64, 192, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
    (4): ReLU(inplace=True)
    (5): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
    (6): Conv2d(192, 384, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (7): ReLU(inplace=True)
    (8): Conv2d(384, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (9): ReLU(inplace=True)
    (10): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): ReLU(inplace=True)
    (12): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (avgpool): AdaptiveAvgPool2d(output_size=(6, 6))
  (classifier): Sequential(
    (0): Dropout(p=0.5, inplace=False)
    (1): Linear(in_features=9216, out_features=4096, bias=True)
 

In [2]:
import torch
import warnings
warnings.filterwarnings("ignore")

In [3]:
torch.cuda.is_available()

True

In [6]:
torch.cuda.get_device_name()

'NVIDIA GeForce GTX 750 Ti'

In [7]:
x = torch.rand(5, 3)
print(x)

tensor([[0.1346, 0.0377, 0.1268],
        [0.1918, 0.2815, 0.5484],
        [0.6454, 0.8762, 0.5755],
        [0.2259, 0.3468, 0.7197],
        [0.1290, 0.4407, 0.9190]])


In [11]:
cuda = torch.device('cuda')

x = torch.tensor([1., 3.]).cuda()
# x.device is device(type='cuda', index=0)
y = torch.tensor([1., 2.]).cuda()


with torch.cuda.device(0):
    # allocates a tensor on GPU 0
    a = torch.tensor([1., 2.], device=cuda)

    # transfers a tensor from CPU to GPU 0
    b = torch.tensor([1., 2.]).cuda()
    # a.device and b.device are device(type='cuda', index=0)

    # You can also use ``Tensor.to`` to transfer a tensor:
    b2 = torch.tensor([1., 2.]).to(device=cuda)
    # b.device and b2.device are device(type='cuda', index=1)

    c = a + b
    print(c)
    # c.device is device(type='cuda', index=0)

    z = x + y
    print(z)
    # z.device is device(type='cuda', index=0)

    # even within a context, you can specify the device
    # (or give a GPU index to the .cuda call)
    d = torch.randn(2, device=cuda)
    print(d)
    # d.device, e.device, and f.device are all device(type='cuda', index=2)

tensor([2., 4.], device='cuda:0')
tensor([2., 5.], device='cuda:0')
tensor([ 0.3448, -0.4560], device='cuda:0')
