In [2]:
import torch
import warnings
warnings.filterwarnings("ignore")

In [3]:
torch.cuda.is_available()

True

In [6]:
torch.cuda.get_device_name()

'NVIDIA GeForce GTX 750 Ti'

In [7]:
x = torch.rand(5, 3)
print(x)

tensor([[0.1346, 0.0377, 0.1268],
        [0.1918, 0.2815, 0.5484],
        [0.6454, 0.8762, 0.5755],
        [0.2259, 0.3468, 0.7197],
        [0.1290, 0.4407, 0.9190]])


In [11]:
cuda = torch.device('cuda')

x = torch.tensor([1., 3.]).cuda()
# x.device is device(type='cuda', index=0)
y = torch.tensor([1., 2.]).cuda()


with torch.cuda.device(0):
    # allocates a tensor on GPU 0
    a = torch.tensor([1., 2.], device=cuda)

    # transfers a tensor from CPU to GPU 0
    b = torch.tensor([1., 2.]).cuda()
    # a.device and b.device are device(type='cuda', index=0)

    # You can also use ``Tensor.to`` to transfer a tensor:
    b2 = torch.tensor([1., 2.]).to(device=cuda)
    # b.device and b2.device are device(type='cuda', index=1)

    c = a + b
    print(c)
    # c.device is device(type='cuda', index=0)

    z = x + y
    print(z)
    # z.device is device(type='cuda', index=0)

    # even within a context, you can specify the device
    # (or give a GPU index to the .cuda call)
    d = torch.randn(2, device=cuda)
    print(d)
    # d.device, e.device, and f.device are all device(type='cuda', index=2)

tensor([2., 4.], device='cuda:0')
tensor([2., 5.], device='cuda:0')
tensor([ 0.3448, -0.4560], device='cuda:0')
